export const FETCH_WEATHER_COORDS_REQUEST = 'FETCH_WEATHER_COORDS_REQUEST'
export const FETCH_WEATHER_COORDS__SUCCESS = 'FETCH_WEATHER_COORDS__SUCCESS'
export const FETCH_WEATHER_COORDS__FAILURE = 'FETCH_WEATHER_COORDS__FAILURE'